Repository pesto-students/batch-11-relayer, pull requests merged in 2019-12, with the labels that each got.

#14 Issue #3 : Added Husky and ESLint
  .eslintrc.json
  client/package.json
  package.json
  server/__test__/index.test.js
  server/app.js
  server/bin/www
  server/package.json
  server/routes/index.js
  server/routes/users.js
  yarn.lock
Labels: New Feature

#49 invalid: Remove the Edit button
  client/src/components/Dashboard/MyApps/MyApps.js
Labels: invalid

#47 feat: Add Task History Details Page
  client/src/Main.js
  client/src/components/Dashboard/CreateNewRelay/CreateNewRelay.js
  client/src/components/Dashboard/TaskHistory/TaskHistoryDetail.js
Labels: New Feature

#51 fix: Add _redirects file to fix Netlify Routing
  client/public/_redirects
Labels: bug

#45 feat: Add Modal to MyApps Page
  client/src/Main.js
  client/src/components/Dashboard/MyApps/MyApps.js
  client/src/components/Dashboard/MyApps/MyAppsHeader.js
  client/src/components/Dashboard/TaskHistory/TaskButton.js
  client/src/components/common/CustomModal.js
  client/src/components/common/index.js
Labels: New Feature

#60 feat: Third party integrations interface done with Slack
  server/__test__/apps.test.js
  server/__test__/user.test.js
  server/app.js
  server/controller/ActionPerformer.js
  server/controller/AppsController.js
  server/controller/IntegrationService.js
  server/controller/RelayController.js
  server/controller/WebHookListeners.js
  server/models/AuthorizedApps.js
  server/models/RelayHistory.js
  server/models/Relays.js
  server/package.json
  server/routes/apps.js
  server/routes/relay.js
  server/thirdparty/controller/DataFetchController.js
  server/thirdparty/controller/SlackActionPerformer.js
  server/thirdparty/controller/SlackDataFetchController.js
  server/thirdparty/controller/SlackTriggerDispatcher.js
  server/thirdparty/controller/slackController.js
  server/thirdparty/integrationConfig.js
  server/thirdparty/routes/DataFetcher.js
  server/thirdparty/routes/slackRouter.js
Labels: New Feature

#72 fix: User Login With Invalid Password
  .idea/workspace.xml
  server/__test__/user.test.js
  server/controller/UserController.js
  server/package.json
Labels: bug

#57 feat: Implement Logic for Protected Routes
  assets/relayer-logo.png
  client/package.json
  client/public/index.html
  client/public/manifest.json
  client/src/Main.js
  client/src/apiUtils/apiCaller.js
  client/src/apiUtils/url.config.js
  client/src/assets/logo/relayer-logo.png
  client/src/assets/styles/components/loading.module.scss
  client/src/assets/styles/components/taskhistory.module.scss
  client/src/components/Dashboard/CreateConfiguration/CreateConfiguration.js
  client/src/components/Dashboard/CreateConfiguration/index.js
  client/src/components/Dashboard/CreateNewRelay/CreateNewRelay.js
  client/src/components/Dashboard/CreateNewRelay/RelaySelection.js
  client/src/components/Dashboard/CreateNewRelay/SelectApp/SelectApp.js
  client/src/components/Dashboard/CreateNewRelay/SelectApp/index.js
  client/src/components/Dashboard/CreateNewRelay/SelectRelay.js
  client/src/components/Dashboard/CreateNewRelay/SelectTrigger/SelectTrigger.js
  client/src/components/Dashboard/CreateNewRelay/SelectTrigger/index.js
  client/src/components/Dashboard/TaskHistory/Filters.js
  client/src/components/Dashboard/TaskHistory/TaskHistory.js
  client/src/components/LandingPage/LandingPage.js
  client/src/components/common/Loading.js
  client/src/components/common/Select.js
  client/src/components/common/index.js
  client/src/index.js
  client/src/store/CreateRelayProvider.js
  client/src/store/reducer.js
  client/src/utils/formatDateUtil.js
  server/app.js
  server/controller/AppsController.js
  yarn.lock
Labels: enhancement

#83 fix: Alignment issue on Create Relay Page
  client/src/components/Dashboard/CreateNewRelay/CreateNewRelay.js
  client/src/components/Dashboard/CreateNewRelay/RelaySelection.js
  client/src/store/CreateRelayProvider.js
Labels: bug

#85 fix: Remove Loader from Create Relay Page
  client/src/apiUtils/url.config.js
  client/src/components/Dashboard/CreateNewRelay/RelaySelection.js
Labels: bug

#86 fix: Add validation
  client/src/components/Dashboard/CreateConfiguration/CreateConfiguration.js
  client/src/components/Dashboard/CreateNewRelay/RelaySelection.js
  client/src/components/Dashboard/ShowAllRelays/ShowAllRelays.js
  client/src/components/LandingPage/LandingPage.js
  client/src/components/common/Select.js
Labels: bug

#88 fix: Bugs
  client/src/Main.js
  client/src/apiUtils/url.config.js
  client/src/components/Authentication/UserAction.js
  client/src/components/Dashboard/CreateConfiguration/CreateConfiguration.js
  client/src/components/Dashboard/ShowAllRelays/ShowAllRelays.js
  client/src/utils/apiCaller.js
  client/src/utils/url.config.js
Labels: bug
